Cloudflare integration
ComposioHQ/composio pull request #260
Opened 2024-07-06 20:27 UTC by anonthedev

Added Cloudflare integration in the sdk

2024-07-06 21:09 UTC, himanshu-dixit requested changes
Remove js files and package-lock

2024-07-06 21:09 UTC, himanshu-dixit commented on js/src/sdk/base.toolset.js
> +                case 4: _.label++; return { value: op[1], done: false };
Remove these files

2024-07-06 21:09 UTC, himanshu-dixit commented on js/examples/ai-playground-main/package-lock.json
> +      }
Remove this

2024-07-07 10:02 UTC, utkarsh-dixit commented
### Pull Request Summary

**Describe the changes of this PR and its objective:**
This PR introduces a new feature integrating Cloudflare framework with ComposioCore to support AI functionality. It adds necessary configuration, dependencies, and examples to demonstrate AI-powered issue creation on GitHub using Cloudflare Workers. 

**Objective:**
- Implement and demonstrate an AI-powered playground using Cloudflare Workers.
- Add support for `Cloudflare` in the core composio library.
- Provide examples and configurations for deploying and testing the Cloudflare-based solution.

**Categorize this PR:**
- **Type:** Feature

**Important change files containing the major logical changes:**
1. `js/examples/ai-playground-main/src/worker.js`
2. `js/src/frameworks/cloudflare.ts`
3. `js/src/index.ts`
4. `js/src/sdk/base.toolset.ts`
5. `js/examples/ai-playground-main/README.md`
6. `js/examples/ai-playground-main/package.json`
7. `js/webpack.config.js`
8. `js/wrangler.toml`

**Code Changes Summary:**
- **New Example:** Added `ai-playground-main` directory containing example Cloudflare worker implementation.
- **Wrangler Config:** Added `wrangler.toml` to configure Cloudflare worker.
- **Dependency Updates:** Added new dependencies such as `composio-core`, `hono`, and `wrangler`.
- **Cloudflare Integration:** Created methods for Cloudflare-specific actions in `cloudflare.ts`.

2024-07-07 20:24 UTC, himanshu-dixit approved these changes

2024-07-07 20:27 UTC, merged