feat: file_uploadable option added
ComposioHQ/composio pull request #288
Opened 2024-07-11 06:31 UTC by sawradip

In case of file upload, (like gmail send attachment), we also need to send the filename. So, this option.

```
    attachment: str = Field(
        ...,
        description="Absolute path of the file to attach",
        json_schema_extra={"file_uploadable": True},
    )
 ```

2024-07-12 06:23 UTC, angrybayblade approved these changes

2024-07-13 08:13 UTC, kaavee315 requested changes
Using @ is so brittle, let's make it a pedantic model or something at least?

2024-07-15 12:10 UTC, kaavee315 approved these changes

2024-07-15 12:45 UTC, kaavee315 approved these changes

2024-07-15 12:48 UTC, merged